spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
      password: 987654
      name: zipkin-server
      username: zipkinuser

server:
  port: 9411
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka